### ISSUE TITLE
Kitten Blocking My Viewport - URGENT BUG

### ISSUE THREAD

**Issue by burgil** [itzalg22/KittensWebsite#1]
#### Issue description
Kitten 2.0 is blocking my view port as can be seen on the screenshots below.

#### Steps to reproduce the issue
1. Clone the repo
2. Cat is blocking the viewport

#### What's the expected result?
- I expected to have full visibly of my screen display after cloning this project.

#### What's the actual result?
- The computer stopped working properly, And before you say it, I already tried to restart it, twice! no luck 😒 

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/41600149/120425356-b11da780-c376-11eb-83a1-df937d95dfc0.png)

**Comment by orrburgel** [comment]
Hahaha that was a fun one to write, Obviously a joke if you didn't get it, Nice first project on GitHub. 🥇 
Contact me if you need some tips and tricks to make your profile stand out more to potential clients. 💯
